In [1]:
import numpy as np

In [99]:
refer = '안녕하'
hyper = '안이하'

In [100]:
d = np.zeros((len(refer)+1) * (len(hyper)+1)).reshape(len(refer)+1, len(hyper)+1) # , dtype=np.int32
# d = np.arange((len(refer)+1) * (len(hyper)+1)).reshape(len(refer)+1, len(hyper)+1) # , dtype=np.int32
d

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [101]:
d[0, ] = np.arange(len(refer)+1)
d.T[0] = np.arange(len(hyper)+1)
d

array([[0., 1., 2., 3.],
       [1., 0., 0., 0.],
       [2., 0., 0., 0.],
       [3., 0., 0., 0.]])

In [121]:
d

array([[0., 1., 2., 3.],
       [1., 0., 0., 0.],
       [2., 0., 0., 0.],
       [3., 0., 0., 0.]])

In [110]:
d.T[0]

array([0., 1., 2., 3.])

In [125]:
for i in range(len(refer) + 1):
    for j in range(len(hyper) + 1):
        if i == 0:
            d[0, j] = j
        elif j == 0:
            d[i][0] = i
for i in range(1, len(refer)+1):
    for j in range(1, len(hyper)+1):
        if refer[i - 1] == hyper[j - 1]:
            d[i][j] = d[i - 1][j - 1]
        else:
            substitute = d[i - 1][j - 1] + 1
            insert = d[i][j - 1] + 1
            delete = d[i - 1][j] + 1
            d[i][j] = min(substitute, insert, delete)

In [124]:
d

array([[0., 1., 2., 3.],
       [1., 0., 1., 2.],
       [2., 1., 1., 2.],
       [3., 2., 2., 1.]])

In [90]:
for j in hyper:
        print(j)

하
이
